#!/bin/sh

url='http://localhost:5000/ci/build'

commit_msg=`git log -n1 --format=%B HEAD`
sha1=`git rev-parse HEAD`
dir=`pwd`

if [[ $commit_msg == *"[NO CI]"* ]];then
    exit 0
fi

curl --data "id=$sha1&git_dir=$dir&msg=$commit_msg" $url
