#!/usr/bin/env python

import subprocess, os, requests
URL="http://localhost:8000/start_ci"

commit_msg = subprocess.check_output(['git', 'log', '--format=%B', '-n' ,'1', 'HEAD'])

if '[NO CI]' in commit_msg:
    exit(0)

sha1 = subprocess.check_output(['git','rev-parse', 'HEAD'])
git_dir = os.getcwd()

payload = {
        'git_dir':git_dir,
        'id':sha1,
        'msg':commit_msg,
        }
print "Commit Detected.\nBuild request sent.\n"
requests.post(URL, json=payload)
