#!/bin/sh

url='http://localhost:5000/ci/build'

commit_msg=`git log -n1 --format=%B HEAD`
sha1=`git rev-parse HEAD`
dir=`pwd`

if [[ $commit_msg == *"[NO CI]"* ]];then
    exit 0
fi

python3.4 $HOME/projects/DockerCI/start_build.py $commit_msg $sha1 $pwd &
disown
